# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Pre-commit's own set of hooks for various utilities
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest version
    hooks:
      - id: trailing-whitespace  # Remove trailing whitespace
      - id: end-of-file-fixer  # Ensures that a file is either empty or ends with one newline
      - id: check-yaml  # Checks YAML files for syntax errors

  # yamllint: Lints YAML files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3  # Use the latest version
    hooks:
      - id: yamllint
        args: [--format=colored, --strict]

  # prettier: An opinionated code formatter that supports YAML
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1  # Use the latest version
    hooks:
      - id: prettier
        args: [--write, --parser=yaml]